<?php
define('MONDAY','01');
define('TUESDAY','02');
define('WEDNESDAY','03');
define('THURSDAY','04');
define('FRIDAY','05');
define('SATURDAY','06');
define('SUNDAY','07');

$LETTER[]='A';
$LETTER[]='B';
$LETTER[]='C';
$LETTER[]='D';
$LETTER[]='E';
$LETTER[]='F';
$LETTER[]='G';
$LETTER[]='H';
$LETTER[]='I';
$LETTER[]='J';
$LETTER[]='K';
?>
